### PR TITLE
Port to 8.4

### PR DESCRIPTION
**Pull request by vlm-ksf**
Same tests failed, but most functionality work

### CODE REVIEW

**Comment by epugh** [comment]
I notice a LOT of files from the sample `collection` that are in this PR, which makes going through it a lot tougher...   @vlm-ksf would you be able to remove those `collection` files down to the minimum required for testing the plugin?  Solr 9 will be stripped down more (no more velocity and other extensions) so having them in this will make it harder to update.   Exciting to see this update!

**Comment by epugh** [comment]
Looks like a lot of clean up!  Do all tests pass?

**Comment by sstults** [comment]
@vlm-ksf and @epugh I'm seeing a couple of things:

- In SwanHighlighterTest there are 28 errors. Given that Solr's unified highlighter is probably much better (or at least a better starting point than where we are), maybe we should shelve the Swan highlighter until we have a better plan

- TestSwanQParserPlugin gave me "Invalid Date String:'Sat Feb 01 00:00:00 AST 1800'". Not sure what's going on there

- TermHighlightComponentTest is unhappy because the term vector request hander "tvrh" is missing. @vlm-ksf did this get deleted by mistake?

**Comment by epugh** [comment]
Is this ready for a build to be set up on CircleCI?

**Comment by sstults** [comment]
@epugh Agreed. There's a CircleCI PR awaiting your review.

@vlm-ksf:
I ran into some weirdness with Solr's preferred PRNG and I suspect you did too. I'm building on a Mac. This seems like something to address in a separate issue though. What JDK version are you building with?

Also, a couple tests needed a "text" field defined, so I added it to the test schema. There were still two tests that failed, but those were in the highlighter and I'm not convinced of their correctness.

@epugh My suggestion is to commit the PR as-is and then make the two smaller changes separately. What's your opinion?

**Comment by epugh** [comment]
What if we create a new branch?   It seems like committing directly to master when things aren't perfect is bad...  We could have a new branch-8x.      Do you think that when Solr 9 comes out, we'll have to modify the parser?  maybe it's good to have 8x, 9x, 10x as branches to follow along with Solr major versions?

**Pull request merged**
